import MODEL_IMAGE_MNIST from './MODEL_IMAGE_MNIST'
import MODEL_IMAGE_MOBILENET from './MODEL_IMAGE_MOBILENET'
import MODEL_IMAGE_RESNET from './MODEL_IMAGE_RESNET'

export {
  MODEL_IMAGE_MNIST,
  MODEL_IMAGE_MOBILENET,
  MODEL_IMAGE_RESNET
}