services:
  nets4learning:
    build:
      context: .
      target: dev-envs
    container_name: nets4learning
    ports:
      - "80:3000"
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock