import I_MODEL_LINEAR_REGRESSION from "./_model";
import MODEL_SALARY from "./MODEL_SALARY"
import MODEL_AUTO_MPG from "./MODEL_AUTO_MPG"
import MODEL_BOSTON_HOUSING from "./MODEL_BOSTON_HOUSING"
import MODEL_BREAST_CANCER from "./MODEL_BREAST_CANCER"
import MODEL_STUDENT_PERFORMANCE from "./MODEL_STUDENT_PERFORMANCE"
import MODEL_WINE from "./MODEL_WINE"

export {
  I_MODEL_LINEAR_REGRESSION,
  MODEL_SALARY,
  MODEL_AUTO_MPG,
  MODEL_BOSTON_HOUSING,
  MODEL_BREAST_CANCER,
  MODEL_STUDENT_PERFORMANCE,
  MODEL_WINE
}