import MODEL_BREAST_CANCER from "./MODEL_BREAST_CANCER"
import MODEL_DIABETES from "./MODEL_DIABETES"
import MODEL_STUDENT_PERFORMANCE from "./MODEL_STUDENT_PERFORMANCE"
import MODEL_WINE from "./MODEL_WINE"

export {
  MODEL_BREAST_CANCER,
  MODEL_DIABETES,
  MODEL_STUDENT_PERFORMANCE,
  MODEL_WINE
}