name: 'Deploy'

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: 'Deploy to netlify'
    runs-on: ubuntu-latest
    steps:
      - name: 'Create env file'
        run: |
          echo "${{ secrets.NETLIFY_ENV_FILE }}" > .env.netlify
      - uses: actions/checkout@v3
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          INSTALL_COMMAND: npm i
          BUILD_COMMAND: npm run build:netlify
          BUILD_DIRECTORY: 'build'
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"